export const SURAHS = [
  { number:1,  name:"الفاتحة",    englishName:"Al-Fatiha",      translation:"L'Ouverture",            ayahs:7,   type:"Mecquoise" },
  { number:2,  name:"البقرة",     englishName:"Al-Baqarah",     translation:"La Vache",               ayahs:286, type:"Médinoise" },
  { number:3,  name:"آل عمران",   englishName:"Al-Imran",       translation:"La Famille d'Imran",     ayahs:200, type:"Médinoise" },
  { number:4,  name:"النساء",     englishName:"An-Nisa",        translation:"Les Femmes",             ayahs:176, type:"Médinoise" },
  { number:5,  name:"المائدة",    englishName:"Al-Maida",       translation:"La Table Servie",        ayahs:120, type:"Médinoise" },
  { number:6,  name:"الأنعام",    englishName:"Al-Anam",        translation:"Les Bestiaux",           ayahs:165, type:"Mecquoise" },
  { number:7,  name:"الأعراف",    englishName:"Al-Araf",        translation:"Les Hauteurs",           ayahs:206, type:"Mecquoise" },
  { number:8,  name:"الأنفال",    englishName:"Al-Anfal",       translation:"Les Butins",             ayahs:75,  type:"Médinoise" },
  { number:9,  name:"التوبة",     englishName:"At-Tawbah",      translation:"Le Repentir",            ayahs:129, type:"Médinoise" },
  { number:10, name:"يونس",       englishName:"Yunus",          translation:"Jonas",                  ayahs:109, type:"Mecquoise" },
  { number:11, name:"هود",        englishName:"Hud",            translation:"Houd",                   ayahs:123, type:"Mecquoise" },
  { number:12, name:"يوسف",       englishName:"Yusuf",          translation:"Joseph",                 ayahs:111, type:"Mecquoise" },
  { number:13, name:"الرعد",      englishName:"Ar-Rad",         translation:"Le Tonnerre",            ayahs:43,  type:"Médinoise" },
  { number:14, name:"إبراهيم",    englishName:"Ibrahim",        translation:"Abraham",                ayahs:52,  type:"Mecquoise" },
  { number:15, name:"الحجر",      englishName:"Al-Hijr",        translation:"Al-Hijr",                ayahs:99,  type:"Mecquoise" },
  { number:16, name:"النحل",      englishName:"An-Nahl",        translation:"Les Abeilles",           ayahs:128, type:"Mecquoise" },
  { number:17, name:"الإسراء",    englishName:"Al-Isra",        translation:"Le Voyage Nocturne",     ayahs:111, type:"Mecquoise" },
  { number:18, name:"الكهف",      englishName:"Al-Kahf",        translation:"La Caverne",             ayahs:110, type:"Mecquoise" },
  { number:19, name:"مريم",       englishName:"Maryam",         translation:"Marie",                  ayahs:98,  type:"Mecquoise" },
  { number:20, name:"طه",         englishName:"Taha",           translation:"Ta-Ha",                  ayahs:135, type:"Mecquoise" },
  { number:21, name:"الأنبياء",   englishName:"Al-Anbiya",      translation:"Les Prophètes",          ayahs:112, type:"Mecquoise" },
  { number:22, name:"الحج",       englishName:"Al-Hajj",        translation:"Le Pèlerinage",          ayahs:78,  type:"Médinoise" },
  { number:23, name:"المؤمنون",   englishName:"Al-Muminun",     translation:"Les Croyants",           ayahs:118, type:"Mecquoise" },
  { number:24, name:"النور",      englishName:"An-Nur",         translation:"La Lumière",             ayahs:64,  type:"Médinoise" },
  { number:25, name:"الفرقان",    englishName:"Al-Furqan",      translation:"Le Critère",             ayahs:77,  type:"Mecquoise" },
  { number:26, name:"الشعراء",    englishName:"Ash-Shuara",     translation:"Les Poètes",             ayahs:227, type:"Mecquoise" },
  { number:27, name:"النمل",      englishName:"An-Naml",        translation:"Les Fourmis",            ayahs:93,  type:"Mecquoise" },
  { number:28, name:"القصص",      englishName:"Al-Qasas",       translation:"Les Récits",             ayahs:88,  type:"Mecquoise" },
  { number:29, name:"العنكبوت",   englishName:"Al-Ankabut",     translation:"L'Araignée",             ayahs:69,  type:"Mecquoise" },
  { number:30, name:"الروم",      englishName:"Ar-Rum",         translation:"Les Romains",            ayahs:60,  type:"Mecquoise" },
  { number:31, name:"لقمان",      englishName:"Luqman",         translation:"Luqman",                 ayahs:34,  type:"Mecquoise" },
  { number:32, name:"السجدة",     englishName:"As-Sajdah",      translation:"La Prosternation",       ayahs:30,  type:"Mecquoise" },
  { number:33, name:"الأحزاب",    englishName:"Al-Ahzab",       translation:"Les Coalisés",           ayahs:73,  type:"Médinoise" },
  { number:34, name:"سبإ",        englishName:"Saba",           translation:"Saba",                   ayahs:54,  type:"Mecquoise" },
  { number:35, name:"فاطر",       englishName:"Fatir",          translation:"Le Créateur",            ayahs:45,  type:"Mecquoise" },
  { number:36, name:"يس",         englishName:"Ya-Sin",         translation:"Yâ-Sîn",                ayahs:83,  type:"Mecquoise" },
  { number:37, name:"الصافات",    englishName:"As-Saffat",      translation:"Rangés en Rangs",        ayahs:182, type:"Mecquoise" },
  { number:38, name:"ص",          englishName:"Sad",            translation:"Sâd",                    ayahs:88,  type:"Mecquoise" },
  { number:39, name:"الزمر",      englishName:"Az-Zumar",       translation:"Les Groupes",            ayahs:75,  type:"Mecquoise" },
  { number:40, name:"غافر",       englishName:"Ghafir",         translation:"Le Pardonneur",          ayahs:85,  type:"Mecquoise" },
  { number:41, name:"فصلت",       englishName:"Fussilat",       translation:"Bien Expliqués",         ayahs:54,  type:"Mecquoise" },
  { number:42, name:"الشورى",     englishName:"Ash-Shura",      translation:"La Consultation",        ayahs:53,  type:"Mecquoise" },
  { number:43, name:"الزخرف",     englishName:"Az-Zukhruf",     translation:"L'Ornement",             ayahs:89,  type:"Mecquoise" },
  { number:44, name:"الدخان",     englishName:"Ad-Dukhan",      translation:"La Fumée",               ayahs:59,  type:"Mecquoise" },
  { number:45, name:"الجاثية",    englishName:"Al-Jathiyah",    translation:"L'Agenouillée",          ayahs:37,  type:"Mecquoise" },
  { number:46, name:"الأحقاف",    englishName:"Al-Ahqaf",       translation:"Les Dunes",              ayahs:35,  type:"Mecquoise" },
  { number:47, name:"محمد",       englishName:"Muhammad",       translation:"Muhammad",               ayahs:38,  type:"Médinoise" },
  { number:48, name:"الفتح",      englishName:"Al-Fath",        translation:"La Victoire",            ayahs:29,  type:"Médinoise" },
  { number:49, name:"الحجرات",    englishName:"Al-Hujurat",     translation:"Les Appartements",       ayahs:18,  type:"Médinoise" },
  { number:50, name:"ق",          englishName:"Qaf",            translation:"Qâf",                    ayahs:45,  type:"Mecquoise" },
  { number:51, name:"الذاريات",   englishName:"Adh-Dhariyat",   translation:"Les Vents Dispersants",  ayahs:60,  type:"Mecquoise" },
  { number:52, name:"الطور",      englishName:"At-Tur",         translation:"Le Mont",                ayahs:49,  type:"Mecquoise" },
  { number:53, name:"النجم",      englishName:"An-Najm",        translation:"L'Étoile",               ayahs:62,  type:"Mecquoise" },
  { number:54, name:"القمر",      englishName:"Al-Qamar",       translation:"La Lune",                ayahs:55,  type:"Mecquoise" },
  { number:55, name:"الرحمن",     englishName:"Ar-Rahman",      translation:"Le Tout Miséricordieux", ayahs:78,  type:"Médinoise" },
  { number:56, name:"الواقعة",    englishName:"Al-Waqia",       translation:"L'Événement",            ayahs:96,  type:"Mecquoise" },
  { number:57, name:"الحديد",     englishName:"Al-Hadid",       translation:"Le Fer",                 ayahs:29,  type:"Médinoise" },
  { number:58, name:"المجادلة",   englishName:"Al-Mujadila",    translation:"La Femme qui Dispute",   ayahs:22,  type:"Médinoise" },
  { number:59, name:"الحشر",      englishName:"Al-Hashr",       translation:"L'Exode",                ayahs:24,  type:"Médinoise" },
  { number:60, name:"الممتحنة",   englishName:"Al-Mumtahanah",  translation:"L'Éprouvée",             ayahs:13,  type:"Médinoise" },
  { number:61, name:"الصف",       englishName:"As-Saf",         translation:"Le Rang",                ayahs:14,  type:"Médinoise" },
  { number:62, name:"الجمعة",     englishName:"Al-Jumuah",      translation:"Le Vendredi",            ayahs:11,  type:"Médinoise" },
  { number:63, name:"المنافقون",  englishName:"Al-Munafiqun",   translation:"Les Hypocrites",         ayahs:11,  type:"Médinoise" },
  { number:64, name:"التغابن",    englishName:"At-Taghabun",    translation:"La Déception Mutuelle",  ayahs:18,  type:"Médinoise" },
  { number:65, name:"الطلاق",     englishName:"At-Talaq",       translation:"Le Divorce",             ayahs:12,  type:"Médinoise" },
  { number:66, name:"التحريم",    englishName:"At-Tahrim",      translation:"L'Interdiction",         ayahs:12,  type:"Médinoise" },
  { number:67, name:"الملك",      englishName:"Al-Mulk",        translation:"La Royauté",             ayahs:30,  type:"Mecquoise" },
  { number:68, name:"القلم",      englishName:"Al-Qalam",       translation:"Le Calame",              ayahs:52,  type:"Mecquoise" },
  { number:69, name:"الحاقة",     englishName:"Al-Haqqah",      translation:"L'Inévitable",           ayahs:52,  type:"Mecquoise" },
  { number:70, name:"المعارج",    englishName:"Al-Maarij",      translation:"Les Degrés",             ayahs:44,  type:"Mecquoise" },
  { number:71, name:"نوح",        englishName:"Nuh",            translation:"Noé",                    ayahs:28,  type:"Mecquoise" },
  { number:72, name:"الجن",       englishName:"Al-Jinn",        translation:"Les Djinns",             ayahs:28,  type:"Mecquoise" },
  { number:73, name:"المزمل",     englishName:"Al-Muzzammil",   translation:"L'Enveloppé",            ayahs:20,  type:"Mecquoise" },
  { number:74, name:"المدثر",     englishName:"Al-Muddaththir", translation:"Le Revêtu d'un Manteau", ayahs:56,  type:"Mecquoise" },
  { number:75, name:"القيامة",    englishName:"Al-Qiyamah",     translation:"La Résurrection",        ayahs:40,  type:"Mecquoise" },
  { number:76, name:"الإنسان",    englishName:"Al-Insan",       translation:"L'Homme",                ayahs:31,  type:"Médinoise" },
  { number:77, name:"المرسلات",   englishName:"Al-Mursalat",    translation:"Les Envoyés",            ayahs:50,  type:"Mecquoise" },
  { number:78, name:"النبإ",      englishName:"An-Naba",        translation:"La Nouvelle",            ayahs:40,  type:"Mecquoise" },
  { number:79, name:"النازعات",   englishName:"An-Naziat",      translation:"Ceux qui Arrachent",     ayahs:46,  type:"Mecquoise" },
  { number:80, name:"عبس",        englishName:"Abasa",          translation:"Il s'est Rembruni",      ayahs:42,  type:"Mecquoise" },
  { number:81, name:"التكوير",    englishName:"At-Takwir",      translation:"L'Enroulement",          ayahs:29,  type:"Mecquoise" },
  { number:82, name:"الانفطار",   englishName:"Al-Infitar",     translation:"La Déchirure",           ayahs:19,  type:"Mecquoise" },
  { number:83, name:"المطففين",   englishName:"Al-Mutaffifin",  translation:"Les Fraudeurs",          ayahs:36,  type:"Mecquoise" },
  { number:84, name:"الانشقاق",   englishName:"Al-Inshiqaq",    translation:"La Fissure",             ayahs:25,  type:"Mecquoise" },
  { number:85, name:"البروج",     englishName:"Al-Buruj",       translation:"Les Constellations",     ayahs:22,  type:"Mecquoise" },
  { number:86, name:"الطارق",     englishName:"At-Tariq",       translation:"L'Astre Nocturne",       ayahs:17,  type:"Mecquoise" },
  { number:87, name:"الأعلى",     englishName:"Al-Ala",         translation:"Le Très Haut",           ayahs:19,  type:"Mecquoise" },
  { number:88, name:"الغاشية",    englishName:"Al-Ghashiyah",   translation:"L'Enveloppante",         ayahs:26,  type:"Mecquoise" },
  { number:89, name:"الفجر",      englishName:"Al-Fajr",        translation:"L'Aube",                 ayahs:30,  type:"Mecquoise" },
  { number:90, name:"البلد",      englishName:"Al-Balad",       translation:"La Cité",                ayahs:20,  type:"Mecquoise" },
  { number:91, name:"الشمس",      englishName:"Ash-Shams",      translation:"Le Soleil",              ayahs:15,  type:"Mecquoise" },
  { number:92, name:"الليل",      englishName:"Al-Layl",        translation:"La Nuit",                ayahs:21,  type:"Mecquoise" },
  { number:93, name:"الضحى",      englishName:"Ad-Duhaa",       translation:"La Matinée",             ayahs:11,  type:"Mecquoise" },
  { number:94, name:"الشرح",      englishName:"Ash-Sharh",      translation:"La Dilatation",          ayahs:8,   type:"Mecquoise" },
  { number:95, name:"التين",      englishName:"At-Tin",         translation:"Le Figuier",             ayahs:8,   type:"Mecquoise" },
  { number:96, name:"العلق",      englishName:"Al-Alaq",        translation:"L'Adhérence",            ayahs:19,  type:"Mecquoise" },
  { number:97, name:"القدر",      englishName:"Al-Qadr",        translation:"La Nuit du Destin",      ayahs:5,   type:"Mecquoise" },
  { number:98, name:"البينة",     englishName:"Al-Bayyinah",    translation:"La Preuve",              ayahs:8,   type:"Médinoise" },
  { number:99, name:"الزلزلة",    englishName:"Az-Zalzalah",    translation:"Le Séisme",              ayahs:8,   type:"Médinoise" },
  { number:100,name:"العاديات",   englishName:"Al-Adiyat",      translation:"Les Coureurs",           ayahs:11,  type:"Mecquoise" },
  { number:101,name:"القارعة",    englishName:"Al-Qariah",      translation:"La Fracassante",         ayahs:11,  type:"Mecquoise" },
  { number:102,name:"التكاثر",    englishName:"At-Takathur",    translation:"La Course aux Richesses",ayahs:8,   type:"Mecquoise" },
  { number:103,name:"العصر",      englishName:"Al-Asr",         translation:"Le Temps",               ayahs:3,   type:"Mecquoise" },
  { number:104,name:"الهمزة",     englishName:"Al-Humazah",     translation:"Le Calomniateur",        ayahs:9,   type:"Mecquoise" },
  { number:105,name:"الفيل",      englishName:"Al-Fil",         translation:"L'Éléphant",             ayahs:5,   type:"Mecquoise" },
  { number:106,name:"قريش",       englishName:"Quraish",        translation:"Les Coraïchites",        ayahs:4,   type:"Mecquoise" },
  { number:107,name:"الماعون",    englishName:"Al-Maun",        translation:"Les Ustensiles",         ayahs:7,   type:"Mecquoise" },
  { number:108,name:"الكوثر",     englishName:"Al-Kawthar",     translation:"L'Abondance",            ayahs:3,   type:"Mecquoise" },
  { number:109,name:"الكافرون",   englishName:"Al-Kafirun",     translation:"Les Mécréants",          ayahs:6,   type:"Mecquoise" },
  { number:110,name:"النصر",      englishName:"An-Nasr",        translation:"Le Secours",             ayahs:3,   type:"Médinoise" },
  { number:111,name:"المسد",      englishName:"Al-Masad",       translation:"La Fibre de Palmier",    ayahs:5,   type:"Mecquoise" },
  { number:112,name:"الإخلاص",    englishName:"Al-Ikhlas",      translation:"Le Monothéisme Pur",     ayahs:4,   type:"Mecquoise" },
  { number:113,name:"الفلق",      englishName:"Al-Falaq",       translation:"L'Aube Naissante",       ayahs:5,   type:"Mecquoise" },
  { number:114,name:"الناس",      englishName:"An-Nas",         translation:"Les Hommes",             ayahs:6,   type:"Mecquoise" },
]
